# === Stage 38: Добавь расширенный набор тестов для ошибок и пограничных случаев ===
# Project: TrainingDeck
def test_edge_cases():
    assert deck.check("int", "  42  ") == "int", "whitespace int"
    assert deck.check("int", "42.5") is None, "float not int"
    assert deck.check("int", "42") == "int", "plain int"
    assert deck.check("str", "  hello  ") == "str", "whitespace str"
    assert deck.check("str", "42") == "str", "digits as str"
    assert deck.check("float", "3.14") == "float", "plain float"
    assert deck.check("float", "3") == "float", "int as float"
    assert deck.check("bool", "True") == "bool", "bool True"
    assert deck.check("bool", "False") == "bool", "bool False"
    assert deck.check("bool", "true") is None, "lowercase bool"
    assert deck.check("bool", "1") is None, "int not bool"
    assert deck.check("list", "[1, 2, 3]") == "list", "list literal"
    assert deck.check("list", "(1, 2, 3)") == "list", "tuple as list"
    assert deck.check("dict", "{'a': 1, 'b': 2}") == "dict", "dict literal"
    assert deck.check("dict", "[1, 2]") is None, "list not dict"
    assert deck.check("none", "None") == "none", "none literal"
    assert deck.check("none", "null") is None, "null not none"
    assert deck.check("set", "{1, 2, 3}") == "set", "set literal"
    assert deck.check("set", "[1, 2]") is None, "list not set"
    assert deck.check("int", "99999999999999999999999999999") == "int", "big int"
    assert deck.check("float", "inf") == "float", "inf"
    assert deck.check("float", "-inf") == "float", "neg inf"
    assert deck.check("float", "nan") == "float", "nan"
    assert deck.check("list", "[]") == "list", "empty list"
    assert deck.check("dict", "{}") == "dict", "empty dict"
    assert deck.check("set", "{}") == "set", "empty set"
    assert deck.check("int", "") is None, "empty str not int"
    assert deck.check("int", "  ") is None, "only spaces not int"
